# -*- mode: ruby -*-
# vi: set ft=ruby :

# number of nodes
N = 2

Vagrant.configure("2") do |config|

  (1..N).each do |i|
    config.vm.define "oracle-9-node-#{i}" do |cfg|
      cfg.vm.box = "oraclelinux/9"
      cfg.vm.box_url = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/9.json"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "oracle-9-node#{i}"
        vb.gui = true
        vb.cpus = 1
        vb.memory = 4096
        vb.customize ["modifyvm", :id, "--groups", "/oracle-9-nodes"]
      end
      cfg.vm.host_name = "node#{i}"
      cfg.vm.network "private_network", ip: "192.168.59.10#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "4010#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    end
  end
end
